# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-18 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongInfo',
            fields=[
                ('song_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='标题')),
                ('img', models.CharField(blank=True, max_length=255, null=True, verbose_name='图片地址')),
                ('author_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='作者')),
                ('album', models.CharField(blank=True, max_length=255, null=True, verbose_name='专辑')),
                ('play_id', models.CharField(max_length=255, null=True, verbose_name='歌单id')),
            ],
        ),
    ]
