# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-18 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songinfo',
            old_name='album',
            new_name='album_title',
        ),
        migrations.AddField(
            model_name='songinfo',
            name='album_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='专辑id'),
        ),
        migrations.AddField(
            model_name='songinfo',
            name='album_img',
            field=models.TextField(blank=True, null=True, verbose_name='专辑img'),
        ),
    ]
