# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-18 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20200418_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True, verbose_name='名称')),
            ],
        ),
    ]
