# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-18 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_songtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='songinfo',
            name='author_one',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='songinfo',
            name='author_three',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='songinfo',
            name='author_two',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
