# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-23 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='电话号码'),
        ),
    ]
