# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-27 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='UsersInfo',
        ),
    ]
