# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-23 07:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_realname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='add_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='playlist_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='歌单id'),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='sing_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='歌手id'),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='song_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='歌曲id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='playlist',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='播放的歌单'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sings',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='播放的歌手'),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
