# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-23 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200423_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='playlist_id',
            field=models.TextField(blank=True, null=True, verbose_name='歌单id'),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='sing_id',
            field=models.TextField(blank=True, null=True, verbose_name='歌手id'),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='song_id',
            field=models.TextField(blank=True, null=True, verbose_name='歌曲id'),
        ),
    ]
