# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-18 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sing', '0002_auto_20200418_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='singinfo',
            name='albumsize',
            field=models.IntegerField(default=0, verbose_name='专辑数量'),
        ),
        migrations.AddField(
            model_name='singinfo',
            name='colletsize',
            field=models.IntegerField(default=0, verbose_name='已收录歌曲数量'),
        ),
        migrations.AddField(
            model_name='singinfo',
            name='img',
            field=models.TextField(blank=True, null=True, verbose_name='图片img'),
        ),
        migrations.AddField(
            model_name='singinfo',
            name='musicsize',
            field=models.IntegerField(default=0, verbose_name='音乐数量'),
        ),
    ]
