# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-27 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingInfo',
            fields=[
                ('sing_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='歌手名称')),
                ('img', models.TextField(blank=True, null=True, verbose_name='图片img')),
                ('musicsize', models.IntegerField(default=0, verbose_name='音乐数量')),
                ('albumsize', models.IntegerField(default=0, verbose_name='专辑数量')),
                ('colletsize', models.IntegerField(default=0, verbose_name='已收录歌曲数量')),
            ],
            options={
                'verbose_name_plural': '歌手信息',
                'db_table': 'SingInfo',
            },
        ),
        migrations.CreateModel(
            name='SingSim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim', models.FloatField(blank=True, verbose_name='相似度')),
                ('sim_sing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_sing', to='sing.SingInfo', verbose_name='相似歌手ID')),
                ('sing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sing.SingInfo', verbose_name='歌手iD')),
            ],
            options={
                'verbose_name_plural': '歌手相似',
                'db_table': 'SingSim',
            },
        ),
        migrations.CreateModel(
            name='SingTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('sing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sing.SingInfo')),
            ],
            options={
                'verbose_name_plural': '歌手类型',
                'db_table': 'SingTag',
            },
        ),
    ]
