# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-20 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingInfo',
            fields=[
                ('sing_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='歌手名称')),
                ('img', models.TextField(blank=True, null=True, verbose_name='图片img')),
                ('musicsize', models.IntegerField(default=0, verbose_name='音乐数量')),
                ('albumsize', models.IntegerField(default=0, verbose_name='专辑数量')),
                ('colletsize', models.IntegerField(default=0, verbose_name='已收录歌曲数量')),
            ],
        ),
    ]
