# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-18 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingInfo',
            fields=[
                ('sing_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='歌手名称')),
            ],
        ),
    ]
