# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-23 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('sing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sing.SingInfo')),
            ],
        ),
    ]
