# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-27 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singsim',
            name='sim_sing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sim_sing', to='sing.SingInfo', verbose_name='相似歌手ID'),
        ),
        migrations.AlterField(
            model_name='singsim',
            name='sing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sing.SingInfo', verbose_name='歌手iD'),
        ),
        migrations.AlterField(
            model_name='singtag',
            name='sing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sing.SingInfo'),
        ),
    ]
