# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-27 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20200427_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songinfo',
            name='author_one',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
