# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-27 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_auto_20200427_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songinfo',
            name='author_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sing.SingInfo'),
        ),
    ]
