# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-27 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayInfo',
            fields=[
                ('play_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='标题')),
                ('img', models.CharField(blank=True, max_length=255, null=True, verbose_name='图片地址')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='作者')),
                ('tag', models.CharField(blank=True, max_length=255, null=True, verbose_name='标签')),
                ('describe', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('collection', models.CharField(blank=True, max_length=255, null=True, verbose_name='收藏量')),
                ('forward', models.CharField(blank=True, max_length=255, null=True, verbose_name='分享量')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='评论量')),
                ('amount', models.CharField(blank=True, max_length=255, null=True, verbose_name='播放量')),
                ('songs', models.TextField(blank=True, null=True, verbose_name='歌单歌曲')),
                ('second_tag', models.IntegerField(default=59)),
                ('thrid_tag', models.IntegerField(default=59)),
            ],
            options={
                'verbose_name_plural': '歌单信息',
                'db_table': 'PlayInfo',
            },
        ),
        migrations.CreateModel(
            name='PlayListSim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim', models.FloatField(blank=True, verbose_name='相似度')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='playlist.PlayInfo', verbose_name='歌单iD')),
                ('sim_playlist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sim_playlist', to='playlist.PlayInfo', verbose_name='相似歌单ID')),
            ],
            options={
                'verbose_name_plural': '歌单相似',
                'db_table': 'PlayListSim',
            },
        ),
        migrations.CreateModel(
            name='PlayListTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('nums', models.IntegerField(default=1, verbose_name='数量')),
            ],
            options={
                'verbose_name_plural': '歌单tag标签',
                'db_table': 'PlayListTag',
            },
        ),
        migrations.AddField(
            model_name='playinfo',
            name='first_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='playlist.PlayListTag'),
        ),
    ]
