# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-28 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playinfo',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='播放量'),
        ),
    ]
